defaults: &defaults
  host: localhost
  autocreate_indexes: true
  # logger: false # Will turn logging off in Mongoid >= 2.2.0

development:
  <<: *defaults
  clients:
    default:
      database: give-a-puck
      hosts:
        - localhost:27017

test:
  <<: *defaults
  clients:
    default:
      database: give-a-puck-test
      hosts:
        - localhost:27017

# production:
#   <<: *defaults
#   clients:
#     default:
#       database: <%= ENV['MONGO_DATABASE'] %>
#       hosts:
#         - <%= "#{ENV['MONGO_HOST']}:#{ENV['MONGO_PORT']}" %>

production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
