development:
  clients:
    default:
      database: give-a-puck
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: give-a-puck-test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

      options:
        # The timeout to wait to execute operations on a socket before raising an error.
        # (default: 5)
        socket_timeout: 10
